platform:ios,’8.0’
target ‘TianlangStar’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 1.0.1'
pod 'MJExtension', '~> 3.0.11'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SDCycleScrollView', '~> 1.65'
end
